spring:

  application:
    name: distributed-transactions-xa-demo

  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update


seata:
  config:
    file:
      name: file.conf